### ISSUE TITLE
页面跳动异常

### ISSUE THREAD

**Issue by Lanxiong** [ddiu8081/chatgpt-demo#128] opened 2023-03-06 05:35 UTC
### Describe the bug

1 当其回答时候  一行一行的数据出来 页面的跳动很怪异 不丝滑
2 当回答所需的字很多时候  回答到一半就停住了  回答不完整 
3 建议输入框 和 问答区域不在同一个滚动范围内 输入框固定在底部就好  

### Reproduction

无

### System Info

```Shell
无
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment] 2023-03-06 05:47
Duplicate of #89

**Closed by ddiu8081** 2023-03-06 05:47 UTC
Labels: duplicate
