### ISSUE TITLE
问代码相关的问题后，返回的结果内容在显示框最右侧显示不完全，然后复制按钮点击不生效

### ISSUE THREAD

**Issue by qizhenghai2020** [ddiu8081/chatgpt-demo#255] opened 2023-03-14 06:44 UTC
### Describe the bug

问代码相关的问题后，返回的结果内容在显示框最右侧显示不完全，然后复制按钮点击不生效

### Reproduction

最新版本

### System Info

```Shell
win10,edge浏览器
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment] 2023-03-14 07:01
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed** 2023-03-14 07:09 UTC
