### ISSUE TITLE
运行后 我开始 对话  返回错误 如图 请问有人遇到过同样的错误吗  An error occurred. fetch failed undici/index.js:109:13

### ISSUE THREAD

**Issue by danggerenba** [ddiu8081/chatgpt-demo#147] opened 2023-03-06 15:54 UTC
### Describe the bug

本人比较小白  mac环境
 npm run dev
运行后 我开始 对话 
但是返回的错误如图
请问有人遇到过同样的错误吗  An error occurred. fetch failed undici/index.js:109:13
<img width="775" alt="image" src="https://user-images.githubusercontent.com/119066997/223161815-648434be-54cf-4871-8b9e-b1577cc1bc31.png">

### Reproduction

An error occurred. fetch failed undici/index.js:109:13

### System Info

```Shell
mac
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by danggerenba** [comment] 2023-03-06 15:59
<img width="615" alt="image" src="https://user-images.githubusercontent.com/119066997/223163506-9088a376-b1b5-4aea-896a-fa5af9ec8ade.png">

**Comment by ddiu8081** [comment] 2023-03-06 16:06
Duplicate of #111. This type of error reporting please follow up in that issue.

在国内本地运行不能直接调用 API，需要自行配置 HTTP 代理并将代理地址配置到 `HTTPS_PROXY` 中，如 `http://127.0.0.1:7890`

**Closed by ddiu8081** 2023-03-06 16:06 UTC
