### ISSUE TITLE
Feat/v2 I suggest adding voice input and output

### ISSUE THREAD

**Issue by TraderGalax** [ddiu8081/chatgpt-demo#382] opened 2023-04-21 10:11 UTC
### Clear and concise description of the problem

Feat/v2 I suggest adding voice input and output

### Suggested solution

Feat/v2 I suggest adding voice input and output

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment] 2023-04-21 10:13
Duplicate of #228

**Closed by ddiu8081** 2023-04-21 10:13 UTC
Labels: enhancement
