### ISSUE TITLE
运行错误如下 请问怎么办  An error occurred. fetch failed undici/index.js:109:13

### ISSUE THREAD

**Issue by danggerenba** [ddiu8081/chatgpt-demo#143] opened 2023-03-06 13:51 UTC
### Describe the bug

<img width="1038" alt="async handleRoute (fileUsersmacDesktoppro" src="https://user-images.githubusercontent.com/119066997/223128552-5909dda5-4e8e-4e04-8a62-e097e0ff11b9.png">

### Reproduction

运行错误如下 请问怎么办  An error occurred. fetch failed undici/index.js:109:13

### System Info

```Shell
运行错误如下 请问怎么办  An error occurred. fetch failed undici/index.js:109:13
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment] 2023-03-06 14:01
Duplicate of #111

**Closed by ddiu8081** 2023-03-06 14:01 UTC
Labels: duplicate
