### ISSUE TITLE
Add a entry to check balance

### ISSUE THREAD

**Issue by longfeng112** [ddiu8081/chatgpt-demo#360] opened 2023-04-11 02:07 UTC
### Clear and concise description of the problem

目前我已经注册了第三个openai账号了, 回顾前两个账号被封的原因,主要是我在访问openai官网时的地址不固定导致的, 而访问openai官网的需求通常是体验新特性或者查询余额, 如果查询余额可以对接到将会使这个项目更具吸引力.

### Suggested solution

期望增加一个查询当前key余额的入口

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yiGmMk** [comment] 2023-04-11 04:12
https://github.com/Yidadaa/ChatGPT-Next-Web 支持查询余额和导出,就是得用vercel部署

**Comment by ddiu8081** [comment] 2023-04-15 09:54
Duplicate of #95

**Closed by ddiu8081** 2023-04-15 09:54 UTC
Labels: enhancement
