### ISSUE TITLE
TypeError An error occurred. fetch failed

### ISSUE THREAD

**Issue by z50913** [ddiu8081/chatgpt-demo#172] opened 2023-03-07 15:02 UTC
### Describe the bug

报错
{
  "name": "ConnectTimeoutError",
  "code": "UND_ERR_CONNECT_TIMEOUT",
  "message": "Connect Timeout Error"
}

![11](https://user-images.githubusercontent.com/78022659/223460383-ce97fe81-bab4-46a8-9dab-ffc21fdfd3b7.png)

### Reproduction

 TypeError An error occurred. fetch failed

### System Info

```Shell
win2012
npm run dev --host 0.0.0.0

docker部署也是报这个错
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment] 2023-03-07 15:05
Duplicate of #111

**Closed by ddiu8081** 2023-03-07 15:05 UTC
