### ISSUE TITLE
save chat history

### ISSUE THREAD

**Issue by xdtxAM** [ddiu8081/chatgpt-demo#120] opened 2023-03-06 01:57 UTC
### Clear and concise description of the problem

1、I hope it is possible to save the chat history and save it as md or pdf
2、I hope that after saving the chat history, I can continue to chat next time and load it

### Suggested solution

no thanks

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment] 2023-03-06 02:34
Duplicate of #21

**Closed by ddiu8081** 2023-03-06 02:34 UTC
Labels: enhancement
