### ISSUE TITLE
希望支持日夜主题切换

### ISSUE THREAD

**Issue by cokice** [ddiu8081/chatgpt-demo#92] opened 2023-03-05 06:49 UTC
### Clear and concise description of the problem

可以手动切换暗色浅色主题

### Suggested solution

可以留个选项手动切换暗色浅色主题

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment] 2023-03-05 07:31
Duplicate of #71

**Closed by ddiu8081** 2023-03-05 07:31 UTC
Labels: enhancement
