### ISSUE TITLE
建议增加GPT-4的支持

### ISSUE THREAD

**Issue by TraderGalax** [ddiu8081/chatgpt-demo#263] opened 2023-03-15 04:45 UTC
### Clear and concise description of the problem

建议增加GPT-4的支持

### Suggested solution

建议增加GPT-4的支持

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment] 2023-03-15 05:35
Duplicate of #258

**Closed by ddiu8081** 2023-03-15 05:35 UTC
Labels: duplicate
