### ISSUE TITLE
Remote connection Refused

### ISSUE THREAD

**Issue by cheniujh** [ddiu8081/chatgpt-demo#296] opened 2023-03-19 12:40 UTC
### Describe the bug

i've deploy this project on my cloud server. when i visit http://myserverIP:3000 using my own PC, it always got ERR_CONNECTION_REFUSED,
i've tries npm run dev -- --0.0.0.0 to run the project, but it dosen't work

### Reproduction

ERR_CONNECTION_REFUSED,

### System Info

```Shell
deploy machine:centos8
remote client:win11
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cheniujh** [comment] 2023-03-20 03:05
i need help

**Comment by yzh990918** [comment] 2023-03-20 11:32
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed** 2023-03-21 08:10 UTC
