### ISSUE TITLE
可以让用户自己填写OPENAI_API_KEY吗

### ISSUE THREAD

**Issue by colorghost** [ddiu8081/chatgpt-demo#329] opened 2023-03-29 02:54 UTC
### Clear and concise description of the problem

可以让用户自己填写OPENAI_API_KEY吗? 和设置系统角色一样. 让用户填写自己的key, 
这样用户请求时候用自己的key就只消耗自己的额度了,

### Suggested solution

和设置系统角色一样,有一个选项栏让用户设置自己的OPENAI_API_KEY

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment] 2023-03-29 02:57
Duplicate of #31

**Closed** 2023-03-29 02:57 UTC
Labels: enhancement
