### ISSUE TITLE
invalid_api_key Incorrect API key provided: undefined. You can find your API key at https://platform.openai.com/account/api-keys.

### ISSUE THREAD

**Issue by Jmlie** [ddiu8081/chatgpt-demo#307] opened 2023-03-21 02:47 UTC
### Describe the bug

在npm和Vercel都尝试可以部署，但相同的openai_api_key用来部署Netlify显示部署不成功，并且报错提醒openai_api_key失效，麻烦请帮忙看看什么问题！
![image](https://user-images.githubusercontent.com/56340333/226506839-d89ac514-7de9-4923-9054-abcf59ba2021.png)

### Reproduction

创建Netlify部署

### System Info

```Shell
invalid_api_key
Incorrect API key provided: undefined. You can find your API key at https://platform.openai.com/account/api-keys.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment] 2023-03-21 02:51
Duplicate of #297

**Closed by ddiu8081** 2023-03-21 02:51 UTC
Labels: duplicate, question, Deploy, Netlify
