### ISSUE TITLE
There is no uniform style for the code styles returned

### ISSUE THREAD

**Issue by luoxiaofeng1029** [ddiu8081/chatgpt-demo#287] opened 2023-03-17 09:22 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/50006313/225864132-9323a2bc-050b-43e7-ac76-e6ae072a2f81.png)
Only the middle section stayed in the right style

### Reproduction

 帮我实现一个网页,里面有一个好看的文本输入框,当鼠标点击进去的时候,它的长度会平滑的增加

### System Info

```Shell
谷歌
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment] 2023-03-17 09:49
Duplicate of https://github.com/ddiu8081/chatgpt-demo/issues/205

**Closed by yzh990918** 2023-03-17 09:49 UTC
