### ISSUE TITLE
I found this website that has the function to manipulate the temperature and Presence Penalty in the user interface, would it be possible to add that function to this project?

### ISSUE THREAD

**Issue by Root-FTW** [ddiu8081/chatgpt-demo#231] opened 2023-03-11 08:20 UTC
### Clear and concise description of the problem

no problem, just feature proposal

### Suggested solution

I found this website that has the function to manipulate the temperature and Presence Penalty in the user interface, would it be possible to add that function to this project?

![image](https://user-images.githubusercontent.com/108767514/224473431-29a3e1dd-7960-43eb-b38b-a73725cd63ca.png)

This is the web site where I found this function:
https://freechatgpt.chat/

this is the source code in case you want to analyze it :)
https://github.com/ztjhz/ChatGPTFreeApp

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment] 2023-03-17 02:42
Duplicate of #87

**Closed by ddiu8081** 2023-03-17 02:42 UTC
Labels: enhancement, V2
