### ISSUE TITLE
TypeError: First parameter has member 'readable' that is not a ReadableStream.

### ISSUE THREAD

**Issue by colin4k** [ddiu8081/chatgpt-demo#167] opened 2023-03-07 09:11 UTC
### Describe the bug

npm run dev

> novel-gpt@0.0.1 dev
> astro dev

file:///home/ubuntu/workspace/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432
		            throw new TypeError(`${context} is not a ReadableStream.`);
		                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (file:///home/ubuntu/workspace/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432:21)
    at convertReadableWritablePair (file:///home/ubuntu/workspace/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3509:11)
    at ReadableStream.pipeThrough (file:///home/ubuntu/workspace/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3584:33)
    at fetchFinale (/home/ubuntu/workspace/chatgpt-demo/node_modules/undici/lib/fetch/index.js:973:52)
    at mainFetch (/home/ubuntu/workspace/chatgpt-demo/node_modules/undici/lib/fetch/index.js:773:5)

### Reproduction

npm run dev

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (2) x64 AMD EPYC 7551 32-Core Processor
    Memory: 592.95 MB / 972.42 MB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.19.1 - /usr/bin/node
    npm: 9.6.0 - /usr/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chenchuyin** [comment] 2023-03-07 09:15
升级nodejs 到 18以上的版本

**Comment by ddiu8081** [comment] 2023-03-07 10:04
Duplicate of #65

**Closed by ddiu8081** 2023-03-07 10:04 UTC
