### ISSUE TITLE
gpt4_api  You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by z50913** [ddiu8081/chatgpt-demo#354] opened 2023-04-06 11:51 UTC
### Describe the bug

找朋友要了个gpt4的api，替换上去报错
![1](https://user-images.githubusercontent.com/78022659/230368376-8640bfa6-45c4-4d43-a704-aa70de478c2a.png)

### Reproduction

gpt

### System Info

```Shell
除了api还需要修改哪里配置么？
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment] 2023-04-06 11:57
Duplicate of #338. 

Please check if you still have a balance in your OpenAI account.

**Closed** 2023-04-06 11:56 UTC
Labels: duplicate
