### ISSUE TITLE
ai has no memory

### ISSUE THREAD

**Issue by CitizenScyu** [ddiu8081/chatgpt-demo#259] opened 2023-03-15 01:15 UTC
### Clear and concise description of the problem

I found that every time I open it, it is a new AI. I can't remember the tuning result, and it will be gone when I open it again. Is there a solution?

### Suggested solution

Can I let my AI remember my training results?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment] 2023-03-15 02:46
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed** 2023-03-16 02:57 UTC
Labels: enhancement
