### ISSUE TITLE
项目运行npm run dev，库node-fetch-native报错  throw new TypeError(`${context} is not a ReadableStream.`)

### ISSUE THREAD

**Issue by chenenkou** [ddiu8081/chatgpt-demo#123] opened 2023-03-06 02:55 UTC
### Describe the bug

按照readm中的步骤，npm i执行了，copy env执行了，执行 npm run dev不久就报错，如下：
file:///Users/m/studyspace/www/ddiu8081_catgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432
		            throw new TypeError(`${context} is not a ReadableStream.`);
		                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (file:///Users/m/studyspace/www/ddiu8081_catgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432:21)
    at convertReadableWritablePair (file:///Users/m/studyspace/www/ddiu8081_catgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3509:11)
    at ReadableStream.pipeThrough (file:///Users/m/studyspace/www/ddiu8081_catgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3584:33)
    at fetchFinale (/Users/m/studyspace/www/ddiu8081_catgpt-demo/node_modules/undici/lib/fetch/index.js:973:52)
    at mainFetch (/Users/m/studyspace/www/ddiu8081_catgpt-demo/node_modules/undici/lib/fetch/index.js:773:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Reproduction

npm run dev

### System Info

```Shell
macOs:13.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lxxxv5** [comment] 2023-03-06 02:57
node 版本 18+

**Comment by JasonFuuuuuuuu** [comment] 2023-03-06 02:57
我也遇到了这个问题，解决不了，估计是node版本问题

**Comment by ddiu8081** [comment] 2023-03-06 02:59
Duplicate of #65

**Closed by ddiu8081** 2023-03-06 02:59 UTC
Labels: duplicate

**Comment by chenenkou** [comment] 2023-03-06 03:02
> node 版本 18+

谢谢，升级后已解决

**Comment by chenenkou** [comment] 2023-03-06 03:03
> Duplicate of #65

谢谢已解决，不过项目中dockerfile中的node:alpine安装后是Node.js v17.3.0，也会执行失败
