### ISSUE TITLE
多chat窗口

### ISSUE THREAD

**Issue by zxitedu** [ddiu8081/chatgpt-demo#223] opened 2023-03-10 11:28 UTC
### Clear and concise description of the problem

我想可以保留多个回话，可以对当前的会话做重命名、删除、添加

### Suggested solution

就像官方的那样

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment] 2023-03-10 11:37
Soon. And Duplicate of #63.

**Closed** 2023-03-10 11:38 UTC
Labels: enhancement
