### ISSUE TITLE
npm run dev 报错 throw new TypeError(`${context} is not a ReadableStream.`);

### ISSUE THREAD

**Issue by jaycethanks** [ddiu8081/chatgpt-demo#192] opened 2023-03-09 01:12 UTC
### Describe the bug

npm run dev, 项目运行不起来

### Reproduction
报错:
throw new TypeError(`${context} is not a ReadableStream.`);

.env
```env
# Your API Key for OpenAI
OPENAI_API_KEY=sk-mPxxxxxxxxxxxxxxxxxM6kl63FeGFMRxxxxxx
# Provide proxy for OpenAI API. e.g. http://127.0.0.1:7890
HTTPS_PROXY=http://127.0.0.1:7890
# Custom base url for OpenAI API. default: https://api.openai.com
OPENAI_API_BASE_URL=
# Inject analytics or other scripts before </head> of the page
HEAD_SCRIPTS=
# Secret string for the project. Use for generating signatures for API calls
SECRET_KEY=
# Set password for site. If not set, site will be public
SITE_PASSWORD=

```

### System Info

```Shell
jayce@jayce:chatgpt-demo$ p run dev

> novel-gpt@0.0.1 dev /home/jayce/Desktop/temp/chatgpt-demo
> astro dev

  🚀  astro  v2.0.15 started in 49ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
file:///home/jayce/Desktop/temp/chatgpt-demo/node_modules/.pnpm/node-fetch-native@1.0.2/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432
                            throw new TypeError(`${context} is not a ReadableStream.`);
                                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (file:///home/jayce/Desktop/temp/chatgpt-demo/node_modules/.pnpm/node-fetch-native@1.0.2/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432:21)
    at convertReadableWritablePair (file:///home/jayce/Desktop/temp/chatgpt-demo/node_modules/.pnpm/node-fetch-native@1.0.2/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3509:11)
    at ReadableStream.pipeThrough (file:///home/jayce/Desktop/temp/chatgpt-demo/node_modules/.pnpm/node-fetch-native@1.0.2/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3584:33)
    at fetchFinale (/home/jayce/Desktop/temp/chatgpt-demo/node_modules/.pnpm/undici@5.20.0/node_modules/undici/lib/fetch/index.js:973:52)
    at mainFetch (/home/jayce/Desktop/temp/chatgpt-demo/node_modules/.pnpm/undici@5.20.0/node_modules/undici/lib/fetch/index.js:773:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ELIFECYCLE  Command failed with exit code 1.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment] 2023-03-09 01:16
Duplicate of #65

**Closed** 2023-03-09 01:17 UTC
Labels: duplicate
