### ISSUE TITLE
invalid_api_key Incorrect API key provided: undefined.

### ISSUE THREAD

**Issue by mufanGuo** [ddiu8081/chatgpt-demo#297] opened 2023-03-20 01:57 UTC
### Describe the bug

我根据md描述，依照Netlify和docker都搭建了应用，但是应用内报了以下错误: invalid_api_key
Incorrect API key provided: undefined. You can find your API key at https://platform.openai.com/account/api-keys.
希望作者可以出一个更加详细的教程 可以解决这些问题，尤其是根据docker，感谢！
![image](https://user-images.githubusercontent.com/39327086/226229120-707d803a-2c03-4bcd-8d16-eb43aed2bca7.png)

### Reproduction

key undefined

### System Info

```Shell
deploy machine:centos7
deploy Docker and Netlify
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cheniujh** [comment] 2023-03-20 02:10
是不是key错了

**Comment by mufanGuo** [comment] 2023-03-20 02:15
我确定key没有错误，因为我替换了两个key，其中一个key在另外一个项目中还在使用中，如果是key错误的话，系统应该提示invalid_api_key Incorrect API key provided: sk-XXXXX，现在明显是应用获取不到key，但我明明在.env配置文件中写入了。

**Comment by yzh990918** [comment] 2023-03-20 02:53
You can try calling the official interface on the postman. If it fails, your key is invalid.

**Comment by irmowan** [comment] 2023-03-20 03:18
Same issue. API Key is correct. I can successfully run it with local pnpm environment. But when I use docker to run it, it says "invalid API key: undefined". 

I have checked the mounted `.env` file, which includes the api key already.
![image](https://user-images.githubusercontent.com/8860292/226238678-5fd92a23-145b-481f-99b2-66a97e41350d.png)

Also, set environment variable doesn't work as well.

**Comment by irmowan** [comment] 2023-03-20 03:24
Reproduction:

1. `git clone git@github.com:ddiu8081/chatgpt-demo.git`
2. `cd chatgpt-demo`
3. `cp .env.example .env`
4. `vi .env` to add api key
5. `docker compose build`
6. `docker compose up -d`
7. Open `localhost:3000` to check. Get `Incorrect API key provided: undefined` error.
Instead of step 5-7, if I use `pnpm install`, `pnpm run dev` to start it, it could successfully work.

**Comment by yzh990918** [comment] 2023-03-20 04:04
ok, I'll check this later.

**Comment by yzh990918** [comment] 2023-03-20 06:57
> Reproduction:
> 
> 1. `git clone git@github.com:ddiu8081/chatgpt-demo.git`
> 2. `cd chatgpt-demo`
> 3. `cp .env.example .env`
> 4. `vi .env` to add api key
> 5. `docker compose build`
> 6. `docker compose up -d`
> 7. Open `localhost:3000` to check. Get `Incorrect API key provided: undefined` error.
>    Instead of steps 5-7, if I use `pnpm install`, `pnpm run dev` to start it, it could successfully work.

Try again?

**Comment by mufanGuo** [comment] 2023-03-20 08:13
Sorry, I still have access errors after deployment. Can I see the env file you configured.

**Comment by irmowan** [comment] 2023-03-20 09:07
@yzh990918 , clean all the work dir and retry works! It is strange. Thanks!

**Comment by yzh990918** [comment] 2023-03-20 11:29
> @yzh990918 , clean all the work dir and retry works! It is strange. Thanks!

Fine, because the environment variable was removed by ignore before. Now it's OK, I'll close this issue.

**Comment by coo1kid1412** [comment] 2023-03-22 07:16
> Sorry, I still have access errors after deployment. Can I see the env file you configured.

the same issue,still failed.你问题解决了么？我看issue closed掉了

**Comment by mufanGuo** [comment] 2023-03-22 07:59
> > Sorry, I still have access errors after deployment. Can I see the env file you configured.
> 
> the same issue,still failed.你问题解决了么？我看issue closed掉了

Not yet, I'm still using the previous version demo image.

**Comment by ddiu8081** [comment] 2023-03-22 08:53
> Not yet, I'm still using the previous version demo image.

@mufanGuo Can you provide your reproduction steps? I tried to follow the steps below and it worked fine.

> Reproduction:
> 
> 1. `git clone git@github.com:ddiu8081/chatgpt-demo.git`
> 2. `cd chatgpt-demo`
> 3. `cp .env.example .env`
> 4. `vi .env` to add api key
> 5. `docker compose build`
> 6. `docker compose up -d`
> 7. Open `localhost:3000` to check. Get `Incorrect API key provided: undefined` error.
>    Instead of steps 5-7, if I use `pnpm install`, `pnpm run dev` to start it, it could successfully work.

**Comment by yzh990918** [comment] 2023-03-22 11:41
> > below
> 
> hi, I deploy it with Netlify: Reproduction:
> 
> 1. fork the repository to my own
> 2. open the https://app.netlify.com/start and import my GitHub account
> 3. intall the netlify for my all repositories
> 4. select the [chatgpt-demo] and all selection is default
> 5. click the “show advanced” and select “New variables” then input “OPENAI_API_KEY“ and the key-value
> 6. click ”Deploy site“
> 7. test still failed：
>    ![image](https://user-images.githubusercontent.com/95113760/226881752-b2327cf7-8df5-4c07-9f7e-e1d11938fb29.png)
> 8. even delete my own repository many times，it doesn't help
> 
> the API key works fine in the [web](https://huggingface.co/) , so it seems the API-key isn‘t the problem

It seems to be your `api-key` problem. We redeployed it again. Everything seems to be normal. I suggest you regenerate a `api-key` and deploy it again.

**Comment by coo1kid1412** [comment] 2023-03-22 12:50
> > Not yet, I'm still using the previous version demo image.
> 
> @mufanGuo @coo1kid1412 Can you provide your reproduction steps? I tried to follow the steps below and it worked fine.
> 
> > Reproduction:
> > 
> > 1. `git clone git@github.com:ddiu8081/chatgpt-demo.git`
> > 2. `cd chatgpt-demo`
> > 3. `cp .env.example .env`
> > 4. `vi .env` to add api key
> > 5. `docker compose build`
> > 6. `docker compose up -d`
> > 7. Open `localhost:3000` to check. Get `Incorrect API key provided: undefined` error.
> >    Instead of steps 5-7, if I use `pnpm install`, `pnpm run dev` to start it, it could successfully work.

hi，it finnaly works by click the icon directly：
![image](https://user-images.githubusercontent.com/95113760/226909486-ba22e99f-5e2c-4fbf-a35e-e3eac7a72d0b.png)

I still have no idea why, jst share the experience FYI

**Comment by kingsh2012** [comment] 2023-03-22 12:59
我使用了这个网站测试(https://huggingface.co/spaces/JavaFXpert/Chat-GPT-LangChain)，api-keys 可以访问。但是我docker-compose下就不行。

**Comment by kingsh2012** [comment] 2023-03-22 13:21
> 我使用了这个网站测试([https://huggingface.co/spaces/JavaFXpert/Chat-GPT-LangChain)，api-keys](https://huggingface.co/spaces/JavaFXpert/Chat-GPT-LangChain)%EF%BC%8Capi-keys) 可以访问。但是我docker-compose下就不行。
我大概知道怎么运行了在docker环境下，先编辑.env文件添加apikeys，添加好以后docker-compose build，每次修改.env以后都要重新build一下。

**Comment by ddiu8081** [comment] 2023-03-22 13:41
> hi, I deploy it with Netlify: Reproduction:
> 
> 1. fork the repository to my own
> 2. open the https://app.netlify.com/start and import my GitHub account
> 3. intall the netlify for my all repositories
> 4. select the [chatgpt-demo] and all selection is default
> 5. click the “show advanced” and select “New variables” then input “OPENAI_API_KEY“ and the key-value
> 6. click ”Deploy site“
> 7. test still failed：
> 8. even delete my own repository many times，it doesn't help

@coo1kid1412 I reproduced the problem using your steps. You can try to trigger deploy manually once in the netlify ui. Then it will get your environment variables.

![ScreenShot 2023-03-22 at 21 39 08@2x](https://user-images.githubusercontent.com/1998168/226922476-d6e11b03-6c5b-4080-bfa4-01708aa9f120.png)

**Comment by mufanGuo** [comment] 2023-03-23 01:23
I have tried to manually trigger deployment in the netlify ui, and now it can be used normally. Thanks for your help!

**Comment by mufanGuo** [comment] 2023-03-23 01:47
> 
Sorry, I find I'm still using the old method to deploy. 
environment: Centos7. 
deploy: Docker
1. pull image
2. docker run .
3. edit the .env
4. docker restart 
Today, I will try using docker compose deployment. I have just installed the plug-in, and I will sync the results here in the future.

**Comment by mufanGuo** [comment] 2023-03-23 01:49
> > Not yet, I'm still using the previous version demo image.
> 
> @mufanGuo @coo1kid1412 Can you provide your reproduction steps? I tried to follow the steps below and it worked fine.
> 
> > Reproduction:
> > 
> > 1. `git clone git@github.com:ddiu8081/chatgpt-demo.git`
> > 2. `cd chatgpt-demo`
> > 3. `cp .env.example .env`
> > 4. `vi .env` to add api key
> > 5. `docker compose build`
> > 6. `docker compose up -d`
> > 7. Open `localhost:3000` to check. Get `Incorrect API key provided: undefined` error.
> >    Instead of steps 5-7, if I use `pnpm install`, `pnpm run dev` to start it, it could successfully work.

Sorry, I find I'm still using the old method to deploy.
environment: Centos7.
deploy: Docker

pull image
docker run .
edit the .env
docker restart
Today, I will try using docker compose deployment. I have just installed the plug-in, and I will sync the results here in the future.

**Comment by ddiu8081** [comment] 2023-03-23 02:39
> Sorry, I find I'm still using the old method to deploy. environment: Centos7. deploy: Docker
> 
> 1. pull image
> 2. docker run .
> 3. edit the .env
> 4. docker restart
> 
> Today, I will try using docker compose deployment. I have just installed the plug-in, and I will sync the results here in the future.

@mufanGuo You can try to edit the .env before running `docker run .`.

**Comment by mufanGuo** [comment] 2023-03-23 08:40
> 

I have tried to edit the .env before running, but still cannot
1. pull image
2. docker create container 
3. docker cp container:/usr/src/.env.example .env
4. vi .env to add api key
5. docker cp .env  container:/usr/src/.env
6. docker start container

**Comment by redteaLi** [comment] 2023-03-28 04:50
@ddiu8081 
直接拉去你的镜像确实有这样的问题 docker pull ghcr.io/ddiu8081/chatgpt-demo:main。
能不能将 读取变量的地方新建一个读取系统环境变量？
import.meta.env.OPENAI_API_KEY 这种方式在docker中读不到环境变量
希望能够将/src/pages/api/generate.ts文件 读取变量改成以下形式
const apiKey = process.env.OPENAI_API_KEY || import.meta.env.OPENAI_API_KEY
这样 docker run -e OPENAI_API_KEY=xxx -p 3000:3000 ghcr.io/ddiu8081/chatgpt-demo:main 就可以生效了

**Comment by yzh990918** [comment] 2023-03-30 06:41
@mufanGuo @kingsh2012  Try https://github.com/ddiu8081/chatgpt-demo#deploy-with-docker

**Comment by mufanGuo** [comment] 2023-03-30 07:34
> @mufanGuo @kingsh2012 Try https://github.com/ddiu8081/chatgpt-demo#deploy-with-docker
@yzh990918 
I tried, but when I pull image through this link https://hub.docker.com/r/ddiu8081/chatgpt-demo, it eroor not found.
So, I pulled the image through the command on this link again：https://github.com/ddiu8081/chatgpt-demo/pkgs/container/chatgpt-demo，succeed!
In addition, the "- d" background execution parameter was not added to the Direct run command in the. md document

**Comment by yzh990918** [comment] 2023-03-30 10:36
> @ddiu8081 直接拉去你的镜像确实有这样的问题 docker pull ghcr.io/ddiu8081/chatgpt-demo:main。 能不能将 读取变量的地方新建一个读取系统环境变量？ import.meta.env.OPENAI_API_KEY 这种方式在docker中读不到环境变量 希望能够将/src/pages/api/generate.ts文件 读取变量改成以下形式 const apiKey = process.env.OPENAI_API_KEY || import.meta.env.OPENAI_API_KEY 这样 docker run -e OPENAI_API_KEY=xxx -p 3000:3000 ghcr.io/ddiu8081/chatgpt-demo:main 就可以生效了

Using process.env will report an error in the Astro project.

**Comment by redteaLi** [comment] 2023-03-30 10:58
> > @ddiu8081 直接拉去你的镜像确实有这样的问题 docker pull ghcr.io/ddiu8081/chatgpt-demo:main。 能不能将 读取变量的地方新建一个读取系统环境变量？ import.meta.env.OPENAI_API_KEY 这种方式在docker中读不到环境变量 希望能够将/src/pages/api/generate.ts文件 读取变量改成以下形式 const apiKey = process.env.OPENAI_API_KEY || import.meta.env.OPENAI_API_KEY 这样 docker run -e OPENAI_API_KEY=xxx -p 3000:3000 ghcr.io/ddiu8081/chatgpt-demo:main 就可以生效了
> 
> Using process.env will report an error in the Astro project.

本地开发环境下是这样的，但是只有前端调用的时候用不了process.env，后端的服务是可以用的。
在utils/auth.ts  文件 generateSignature 方法下面这一行会报错。
 const secretKey = import.meta.env.PUBLIC_SECRET_KEY ?? process.env.PUBLIC_SECRET_KEY as string

 
 看了一下你的最新commit 
 docker run --name=chatgpt-demo --volume=/path/.env:/usr/src/.env:rw -p 3000:3000 --restart=always -d ddiu8081/chatgpt-demo:latest
 这个方式配置的 .env 是不会生效的，原因docker 打包成镜像以后就不会读取源码文件夹下的文件。


或者修改Dockerfile最后一行 cmd 是 “npm run dev”  对应的package.json 文件 dev  添加 --host，原因：Astro默认不会暴露在局域网中，use --host to expose。
这个方法我没具体验证过。

**Comment by yzh990918** [comment] 2023-03-31 04:44
I and diu are not very familiar with Docker. If you have a solution, welcome to submit a pull request.

**Comment by yzh990918** [comment] 2023-03-31 04:46
> > > @ddiu8081 直接拉去你的镜像确实有这样的问题 docker pull ghcr.io/ddiu8081/chatgpt-demo:main。 能不能将 读取变量的地方新建一个读取系统环境变量？ import.meta.env.OPENAI_API_KEY 这种方式在docker中读不到环境变量 希望能够将/src/pages/api/generate.ts文件 读取变量改成以下形式 const apiKey = process.env.OPENAI_API_KEY || import.meta.env.OPENAI_API_KEY 这样 docker run -e OPENAI_API_KEY=xxx -p 3000:3000 ghcr.io/ddiu8081/chatgpt-demo:main 就可以生效了
> > 
> > 
> > Using process.env will report an error in the Astro project.
> 
> 本地开发环境下是这样的，但是只有前端调用的时候用不了process.env，后端的服务是可以用的。 在utils/auth.ts 文件 generateSignature 方法下面这一行会报错。 const secretKey = import.meta.env.PUBLIC_SECRET_KEY ?? process.env.PUBLIC_SECRET_KEY as string
> 
> 看了一下你的最新commit docker run --name=chatgpt-demo --volume=/path/.env:/usr/src/.env:rw -p 3000:3000 --restart=always -d ddiu8081/chatgpt-demo:latest 这个方式配置的 .env 是不会生效的，原因docker 打包成镜像以后就不会读取源码文件夹下的文件。
> 
> 或者修改Dockerfile最后一行 cmd 是 “npm run dev” 对应的package.json 文件 dev 添加 --host，原因：Astro默认不会暴露在局域网中，use --host to expose。 这个方法我没具体验证过。

The first `docker run` is still valid, but it's really inconvenient to have to re-do the env file and then re-run it every time.

**Comment by immatur1ty** [comment] 2023-04-02 15:44
> > Not yet, I'm still using the previous version demo image.
> 
> @mufanGuo @coo1kid1412 Can you provide your reproduction steps? I tried to follow the steps below and it worked fine.
> 
> > Reproduction:
> > 
> > 1. `git clone git@github.com:ddiu8081/chatgpt-demo.git`
> > 2. `cd chatgpt-demo`
> > 3. `cp .env.example .env`
> > 4. `vi .env` to add api key
> > 5. `docker compose build`
> > 6. `docker compose up -d`
> > 7. Open `localhost:3000` to check. Get `Incorrect API key provided: undefined` error.
> >    Instead of steps 5-7, if I use `pnpm install`, `pnpm run dev` to start it, it could successfully work.

Same steps and same issue. I have also switched to npm for now, docker seems not to read settings from source codes even using `docker compose build`.

**Comment by A7103** [comment] 2023-04-04 04:28
I built the image locally and started it, and it worked fine. Here are the steps I followed: 

1. Generated and configured the .env file locally.
2. Modified the image in the docker-compose.yml file from `image: ddiu8081/chatgpt-demo:latest` to `image: chatgpt-demo:latest`.
3. Ran the command `docker build -t chatgpt-demo:latest` . to build a new image.
4. Used the command `docker-compose up -d` to start (or `docker run --name chatgpt-demo chatgpt-demo:latest`).
---

It seems that the reason why running `docker-compose up -d` directly cannot be used is that the program cannot read the Key and needs to be specified before building, I'm not familiar with FE technology, just a guess.

**Comment by yangsijie666** [comment] 2023-04-04 08:09
Hi @yzh990918 ：

**Comment by yzh990918** [comment] 2023-04-04 08:44
> Hi @yzh990918 ：
> 
> I've submitted a pull request that should fix this issue. You can find the PR [here](https://github.com/ddiu8081/chatgpt-demo/pull/347). Please take a look and let me know if there's anything else I can do to help. I'd be happy to make any necessary changes to get this merged as soon as possible.
> 
> PS: Anyone who encounters this problem can temporarily replace the container image with `fightingsj/chatgpt-demo:container-fix`.
> 
> Docker run command should be like: `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`

This modification will cause an error locally, as mentioned above.

**Comment by 98games** [comment] 2023-04-04 09:46
我也遇到了vi env 不能正确读取apikey

**Comment by mufanGuo** [comment] 2023-04-04 09:48
> 我也遇到了vi env 不能正确读取apikey

You can see it->https://github.com/ddiu8081/chatgpt-demo/issues/297#issuecomment-1495532372

**Comment by nfzsh** [comment] 2023-04-05 12:20
> > > Hi @yzh990918 ：
> > > I've submitted a pull request that should fix this issue. You can find the PR [here](https://github.com/ddiu8081/chatgpt-demo/pull/347). Please take a look and let me know if there's anything else I can do to help. I'd be happy to make any necessary changes to get this merged as soon as possible.
> > > PS: Anyone who encounters this problem can temporarily replace the container image with `fightingsj/chatgpt-demo:container-fix`.
> > > Docker run command should be like: `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`
> > 
> > 
> > This modification will cause an error locally, as mentioned above. Astro not support the syntax of `process.env`.
> 
> Hi @yzh990918 ，I found another way to solve this problem, dynamically replace the file content in `dist` according to the environment variable before the application starts, see this [PR](https://github.com/ddiu8081/chatgpt-demo/pull/349) for details.
> 
> PS: Anyone who encounters this problem can temporarily replace the container image with `fightingsj/chatgpt-demo:container-fix-v2`.
> 
> Docker run command should be like: `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
> 
> 
> > > 嗨 @yzh990918 ：
> > > 我已经提交了一个pull request，应该可以解决这个问题。你可以找到PR [这里](https://github.com/ddiu8081/chatgpt-demo/pull/347).请看一下，如果还有什么我能帮忙的，请告诉我。我很乐意做任何必要的修改，以尽快合并。
> > > PS：遇到这个问题的人可以暂时用`fightingsj/chatgpt-demo:container-fix`替换容器镜像。
> > > Docker run命令应该像这样：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`
> > 
> > 
> > 如上所述，此修改将导致本地错误。Astro不支持`process.env`的语法。
> 
> 嗨 @yzh990918 ，我找到了另一个解决这个问题的方法，在应用启动前根据环境变量动态替换`dist`中的文件内容，看到这个 [PR](https://github.com/ddiu8081/chatgpt-demo/pull/349) 了解详情。
> 
> PS： 遇到此问题的任何人都可以暂时将容器映像替换为`fightingsj/chatgpt-demo:container-fix-v2`。
> 
> Docker run命令应该像这样： `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`

But the env “SITE_PASSWORD” variable still doesn't take effect.

**Comment by yangsijie666** [comment] 2023-04-05 14:17
> > > > Hi @yzh990918 ：
> > > > I've submitted a pull request that should fix this issue. You can find the PR [here](https://github.com/ddiu8081/chatgpt-demo/pull/347). Please take a look and let me know if there's anything else I can do to help. I'd be happy to make any necessary changes to get this merged as soon as possible.
> > > > PS: Anyone who encounters this problem can temporarily replace the container image with `fightingsj/chatgpt-demo:container-fix`.
> > > > Docker run command should be like: `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`
> > > 
> > > 
> > > This modification will cause an error locally, as mentioned above. Astro not support the syntax of `process.env`.
> > 
> > 
> > Hi @yzh990918 ，I found another way to solve this problem, dynamically replace the file content in `dist` according to the environment variable before the application starts, see this [PR](https://github.com/ddiu8081/chatgpt-demo/pull/349) for details.
> > PS: Anyone who encounters this problem can temporarily replace the container image with `fightingsj/chatgpt-demo:container-fix-v2`.
> > Docker run command should be like: `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
> > > > 嗨 @yzh990918 ：
> > > > 我已经提交了一个pull request，应该可以解决这个问题。你可以找到PR [这里](https://github.com/ddiu8081/chatgpt-demo/pull/347).请看一下，如果还有什么我能帮忙的，请告诉我。我很乐意做任何必要的修改，以尽快合并。
> > > > PS：遇到这个问题的人可以暂时用`fightingsj/chatgpt-demo:container-fix`替换容器镜像。
> > > > Docker run命令应该像这样：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`
> > > 
> > > 
> > > 如上所述，此修改将导致本地错误。Astro不支持`process.env`的语法。
> > 
> > 
> > 嗨 @yzh990918 ，我找到了另一个解决这个问题的方法，在应用启动前根据环境变量动态替换`dist`中的文件内容，看到这个 [PR](https://github.com/ddiu8081/chatgpt-demo/pull/349) 了解详情。
> > PS： 遇到此问题的任何人都可以暂时将容器映像替换为`fightingsj/chatgpt-demo:container-fix-v2`。
> > Docker run命令应该像这样： `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
> 
> But the env “SITE_PASSWORD” variable still doesn't take effect.

I've tested it, and it's supportive. `-e` can be used multiple times in docker run command to declare multiple environment variables.

Docker run command should be like: `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -e SITE_PASSWORD=YOUR_SITE_PASSWORD -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`

**Comment by lvshp** [comment] 2023-04-06 02:24
> > > > > 你好@yzh990918：
> > > > > 我提交了一个pull request应该可以解决这个问题。[您可以在此处](https://github.com/ddiu8081/chatgpt-demo/pull/347)找到 PR 。请看一看，如果还有什么我可以帮忙的，请告诉我。我很乐意做出任何必要的更改以尽快将其合并。
> > > > > PS：遇到这个问题的可以暂时把容器镜像换成`fightingsj/chatgpt-demo:container-fix`. 
> > > > > Docker 运行命令应该是这样的：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`
> > > > 
> > > > 
> > > > 这个修改会导致本地报错，上面说了。Astro 不支持`process.env`.
> > > 
> > > 
> > > 你好@yzh990918`dist`，我找到了另一种方法来解决这个问题，在应用启动前根据环境变量动态替换里面的文件内容，详见这个[PR 。](https://github.com/ddiu8081/chatgpt-demo/pull/349)
> > > PS：遇到这个问题的可以暂时把容器镜像换成`fightingsj/chatgpt-demo:container-fix-v2`. 
> > > Docker 运行命令应该是这样的：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
> > > > > 嗨 @yzh990918 ：
> > > > > 我已经提交了一个pull request，应该可以解决这个问题。你可以找到PR [这里](https://github.com/ddiu8081/chatgpt-demo/pull/347).请看一下，如果还有什么我能帮忙的，请告诉我。我很乐意做任何必要的修改，以尽快合并。
> > > > > PS：遇到这个问题的人可以暂时用`fightingsj/chatgpt-demo:container-fix`替换容器镜像。
> > > > > Docker run命令应该像这样：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`
> > > > 
> > > > 
> > > > 如上所述，此修改将导致本地错误。Astro不支持`process.env`的语法。
> > > 
> > > 
> > > 嗨@yzh990918 ，我找到了另一个解决这个问题的方法，在应用启动前根据环境变量动态替换`dist`中的文件内容，看到这个 [PR](https://github.com/ddiu8081/chatgpt-demo/pull/349) 了解详情。
> > > PS： 遇到此问题的任何人都可以暂时将容器映像替换为`fightingsj/chatgpt-demo:container-fix-v2`。
> > > Docker run命令应该像这样： `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
> > 
> > 
> > 但是 env “SITE_PASSWORD” 变量仍然没有生效。
> 
> 我已经测试过了，它是支持的。`-e`可以在 docker run 命令中多次使用，声明多个环境变量。
> 
> Docker 运行命令应该是这样的：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -e SITE_PASSWORD=YOUR_SITE_PASSWORD -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`

你好，我运行了这个docker命令 `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -e SITE_PASSWORD=YOUR_SITE_PASSWORD -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
到这一步有个warning报错 `Status: Downloaded newer image for fightingsj/chatgpt-demo:container-fix-v2`
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
然后status一直是Exited (1) ,运行 `docker run chatgpt-demo`也无法启动
服务器是oralce cloud的免费服务器 arm的处理器
系统环境：Ubuntu 20.04.5 LTS 
对docker不是很熟，可以帮我看下什么问题吗

**Comment by lvshp** [comment] 2023-04-06 03:14
> > > > > > 你好@yzh990918：
> > > > > > 我提交了一个pull request应该可以解决这个问题。[您可以在此处](https://github.com/ddiu8081/chatgpt-demo/pull/347)找到 PR 。请看一看，如果还有什么我可以帮忙的，请告诉我。我很乐意做出任何必要的更改以尽快将其合并。
> > > > > > PS：遇到这个问题的可以暂时把容器镜像换成`fightingsj/chatgpt-demo:container-fix`.
> > > > > > Docker 运行命令应该是这样的：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`
> > > > > 
> > > > > 
> > > > > 这个修改会导致本地报错，上面说了。Astro 不支持`process.env`.
> > > > 
> > > > 
> > > > 你好@yzh990918`dist`，我找到了另一种方法来解决这个问题，在应用启动前根据环境变量动态替换里面的文件内容，详见这个[PR 。](https://github.com/ddiu8081/chatgpt-demo/pull/349)
> > > > PS：遇到这个问题的可以暂时把容器镜像换成`fightingsj/chatgpt-demo:container-fix-v2`.
> > > > Docker 运行命令应该是这样的：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
> > > > > > 嗨 @yzh990918 ：
> > > > > > 我已经提交了一个pull request，应该可以解决这个问题。你可以找到PR [这里](https://github.com/ddiu8081/chatgpt-demo/pull/347).请看一下，如果还有什么我能帮忙的，请告诉我。我很乐意做任何必要的修改，以尽快合并。
> > > > > > PS：遇到这个问题的人可以暂时用`fightingsj/chatgpt-demo:container-fix`替换容器镜像。
> > > > > > Docker run命令应该像这样：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix`
> > > > > 
> > > > > 
> > > > > 如上所述，此修改将导致本地错误。Astro不支持`process.env`的语法。
> > > > 
> > > > 
> > > > 嗨@yzh990918 ，我找到了另一个解决这个问题的方法，在应用启动前根据环境变量动态替换`dist`中的文件内容，看到这个 [PR](https://github.com/ddiu8081/chatgpt-demo/pull/349) 了解详情。
> > > > PS： 遇到此问题的任何人都可以暂时将容器映像替换为`fightingsj/chatgpt-demo:container-fix-v2`。
> > > > Docker run命令应该像这样： `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
> > > 
> > > 
> > > 但是 env “SITE_PASSWORD” 变量仍然没有生效。
> > 
> > 
> > 我已经测试过了，它是支持的。`-e`可以在 docker run 命令中多次使用，声明多个环境变量。
> > Docker 运行命令应该是这样的：`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -e SITE_PASSWORD=YOUR_SITE_PASSWORD -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2`
> 
> 你好，我运行了这个docker命令 `docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -e SITE_PASSWORD=YOUR_SITE_PASSWORD -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2` 到这一步有个warning报错 `Status: Downloaded newer image for fightingsj/chatgpt-demo:container-fix-v2` `WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested` 然后status一直是Exited (1) ,运行 `docker run chatgpt-demo`也无法启动 服务器是oralce cloud的免费服务器 arm的处理器 系统环境：Ubuntu 20.04.5 LTS 对docker不是很熟，可以帮我看下什么问题吗

我在reddit上找到了解决方法
执行 `docker run --privileged --rm tonistiigi/binfmt --install all` 命令后再执行`docker run --name=chatgpt-demo -e OPENAI_API_KEY=YOUR_OPEN_API_KEY -e SITE_PASSWORD=YOUR_SITE_PASSWORD -p 3000:3000 -d fightingsj/chatgpt-demo:container-fix-v2` 现在AI已经正常运行了

**Comment by licc12** [comment] 2023-04-09 15:06
我解决了，方案如下：
![image](https://user-images.githubusercontent.com/28993145/230780532-3fc81035-07d7-4729-b0fa-d27ecda2cdaa.png)
这是在网站https://app.netlify.com/部署时的处理方案，部署完之后，这里的openai_key是空的，需要在此处编辑，然后重新填入apikey即可；

**Closed** 2023-04-11 02:19 UTC
Labels: bug, Deploy, Netlify, docker
