### ISSUE TITLE
希望能支持在页面填入key, 存到localStorage就行

### ISSUE THREAD

**Issue by vaynevayne** [ddiu8081/chatgpt-demo#248] opened 2023-03-13 05:36 UTC
### Clear and concise description of the problem

朋友也有账号,但是不想部署的麻烦, 就全用我的, 我的key顶不住, 搞个输入框,让他们填他们自己的,

### Suggested solution

也可以灵活点, 搞了环境变量, 是否显示输入框, 显示的话,就必须填,

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment] 2023-03-13 05:43
Duplicate of #31

**Closed by ddiu8081** 2023-03-13 05:43 UTC
Labels: enhancement
