### ISSUE TITLE
Not work with the customized domain on Vercel

### ISSUE THREAD

**Issue by pjq** [ddiu8081/chatgpt-demo#169] opened 2023-03-07 13:53 UTC
### Describe the bug

1. Deploy and running on the Vercel.
2. The Auto assigned domain works well
3.  But when I use the customized domain, it doesn't work, it seems can load the website, but it shows some error 
4. Have try the `chatgpt-vercel`, the same error

- The domain
```
echo "aHR0cHM6Ly9jaGF0LnBqcS5tZS8K"|base64 -d
```

- Click all the button/settings, no response.
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/87846/223439921-393606cc-a1e2-4413-ae70-c991aa139810.png">

### Reproduction

Deploy and running on the Vercel

### System Info

```Shell
Vercel
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ddiu8081** [comment] 2023-03-07 15:12
Duplicate of #134

**Closed by ddiu8081** 2023-03-07 15:12 UTC
